apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    mockorbit.duckdns.org {
      reverse_proxy 34.47.243.197:80
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy-reverse-proxy
  template:
    metadata:
      labels:
        app: caddy-reverse-proxy
    spec:
      containers:
      - name: caddy
        image: caddy:2
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - name: caddy-config
          mountPath: /etc/caddy
      volumes:
      - name: caddy-config
        configMap:
          name: caddy-config

---
apiVersion: v1
kind: Service
metadata:
  name: caddy-service
spec:
  type: LoadBalancer
  selector:
    app: caddy-reverse-proxy
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
