apiVersion: v1
kind: Service
metadata:
  name: mockorbit-backend-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 34.47.243.197
  selector:
    app: mockorbit
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
